'uglify-js' NPM package has been upgraded to (incompatible) UglifyJS2
It's explained here https://github.com/mishoo/UglifyJS#install-npm

Which gives us:

error: /javascripts/jquery-1.8.3.js TypeError: Cannot call method 'parse' of undefined
warning: "GET /javascripts/jquery-1.8.3.js" 200 - Failed to Minify
GET /javascripts/jquery-1.8.3.js 200 23ms - 259.82kb

Instead of:

info: "GET /javascripts/jquery-1.8.3.js" 200 - Minified
GET /javascripts/jquery-1.8.3.js 200 3599ms - 91.38kb
debug: Cached uglified: /javascripts/jquery-1.8.3.js